CREATE DATABASE kinopoisk

CREATE TABLE film (
        filmId int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name VARCHAR(50) NOT NULL,
        description text NOT NULL,
		Grade real NOT NULL,
	    numberRatings int NOT NULL,
		NumberReviews int NOT NULL,
        AudioTracks VARCHAR(50) NOT NULL,
        Subtitles VARCHAR(50) NOT NULL,
        quality VARCHAR(10) NOT NULL,
        ProductionYear int NOT NULL,
        ProductionCountry VARCHAR(30) NOT NULL,
        tagline text NOT NULL,
        budget int NOT NULL,
        marketing  int NOT NULL,
        USfees int NOT NULL,
        feesWorld int NOT NULL,
        premiereRussia date NOT NULL,
        premiereWorld date NOT NULL,
        ReleaseDVD date NOT NULL,
		minAge int NOT NULL,
	    RatingMPAA VARCHAR(10) NOT NULL,        
        time time NOT NULL
    );
	
INSERT INTO film
VALUES (1, 'Зеленая миля', 'В тюрьме для смертников появляется заключенный с божественным даром. Мистическая драма по роману Стивена Кинга',
		9.1, 865997, 475, 'Русский, Английский', 'Русские', 'Full HD',  1999, 'США', '«Пол Эджкомб не верил в чудеса. Пока не столкнулся с одним из них»',
	   60000000, 30000000, 136801374, 150000000, '2000-04-18', '1999-12-06', '2001-02-13', 16, 'R', '03:09:00.0000' );

CREATE TABLE filmPerson (
    filmPersonId int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    personName VARCHAR(100) NOT NULL,
    roleType VARCHAR(20) 
	CHECK(roleType IN('В главных ролях','Роли дублировали'))
);
    
INSERT INTO filmPerson (personName, roleType)
VALUES ('Том Хэнкс', 'В главных ролях'),
		('Дэвид Морс', 'В главных ролях'),
		('Бонни Хант', 'В главных ролях'),
		('Майкл Кларк Дункан', 'В главных ролях'),
		('Джеймс Кромуэлл', 'В главных ролях'),
		('Майкл Джитер', 'В главных ролях'),
		('Грэм Грин', 'В главных ролях'),
		('Даг Хатчисон', 'В главных ролях'),
		('Сэм Рокуэлл', 'В главных ролях'),
		('Барри Пеппер', 'В главных ролях'),
		('Всеволод Кузнецов', 'Роли дублировали'),
		('Владимир Антоник', 'Роли дублировали'),
		('Любовь Германова', 'Роли дублировали'),
		('Валентин Голубенко', 'Роли дублировали'),
		('Александр Белявский', 'Роли дублировали');



CREATE TABLE film_filmPerson (
        filmId int references film(filmId),
        filmPersonId int references filmPerson(filmPersonId),
        constraint film_filmPerson_pkey primary key (filmId, filmPersonId)     
    );



INSERT INTO film_filmPerson (filmId, filmPersonId)
VALUES (1, 1),
		(1, 2),
		(1, 3),
		(1, 4),
		(1, 5),
		(1, 6),
		(1, 7),
		(1, 8),
		(1, 9),
		(1, 10),
		(1, 11),
		(1, 12),
		(1, 13),
		(1, 14),
		(1, 15);


CREATE TABLE person (
        PersonId int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        personName VARCHAR(50) NOT NULL,
        FilmWork VARCHAR(20) NOT NULL,
        filmId int NOT NULL,
		constraint person_film foreign key (filmId) references film(filmId)
    );



INSERT INTO person (personName, FilmWork, filmId)
VALUES ('Фрэнк Дарабонт', 'Режиссер', 1),
('Стивен Кинг', 'Сценарий', 1),
('Дэвид Валдес', 'Продюсер', 1),
('Дэвид Тэттерсолл', 'Оператор', 1),
('Томас Ньюман', 'Композитор', 1),
('Теренс Марш', 'Художник', 1),
('Ричард Фрэнсис-Брюс', 'Монтаж', 1);


CREATE TABLE genre (
        genreId int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        genre_type VARCHAR(50) NOT NULL
    );

INSERT INTO genre (genre_type)
VALUES ('драма'),
        ('фэнтези'),
        ('криминал');



CREATE TABLE film_genre (
        filmId int references film(filmId),
        genreId int references genre(genreId),
        constraint film_genre_pkey primary key (filmId, genreId)             
    );

INSERT INTO film_genre (filmId, genreId)
VALUES (1, 1),
		(1, 2),
		(1, 3);

CREATE TABLE spectators (
        spectatorsId int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        country VARCHAR(70) NOT NULL,
        quantity int,
        filmId int NOT NULL,
		constraint person_film foreign key (filmId) references film(filmId)
    );

    INSERT INTO spectators (country, quantity, filmId)
VALUES ('США', 26000000, 1),
        ('Германия', 2107877, 1),
        ('Греция', 182000, 1),
        ('Норвегия', 110510, 1),
        ('Финляндия', 32953, 1),
        ('Швеция', 132085, 1),
        ('Италия', 	1742730, 1),
        ('Франция', 1714080, 1),
        ('Испания', 692551, 1);