CREATE DATABASE kinopoisk



DROP TABLE film_film_person;
DROP TABLE film_person;
DROP TABLE role;
DROP TABLE person;
DROP TABLE job;
DROP TABLE film_genre;
DROP TABLE genre;
DROP TABLE spectators;
DROP TABLE country;
DROP TABLE film;



CREATE TABLE film (
        id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name VARCHAR(50) NOT NULL,
        description text NOT NULL,
		grade real NOT NULL,
	    ratings int NOT NULL,
		reviews int NOT NULL,
        audio_tracks VARCHAR(50) NOT NULL,
        subtitles VARCHAR(50) NOT NULL,
        quality VARCHAR(10) NOT NULL,
        year int NOT NULL,
        country VARCHAR(30) NOT NULL,
        tagline text NOT NULL,
        budget int NOT NULL,
        marketing  int NOT NULL,
        us_fees int NOT NULL,
        fees_world int NOT NULL,
        premiere_russia date NOT NULL,
        premiere_world date NOT NULL,
        release_dvd date NOT NULL,
		min_age int NOT NULL,
	    mpa VARCHAR(10) NOT NULL,        
        time time NOT NULL
    );
	
INSERT INTO film
VALUES (1, 'Зеленая миля', 'В тюрьме для смертников появляется заключенный с божественным даром. Мистическая драма по роману Стивена Кинга',
		9.1, 865997, 475, 'Русский, Английский', 'Русские', 'Full HD',  1999, 'США', '«Пол Эджкомб не верил в чудеса. Пока не столкнулся с одним из них»',
	   60000000, 30000000, 136801374, 150000000, '2000-04-18', '1999-12-06', '2001-02-13', 16, 'R', '03:09:00.0000' );



CREATE TABLE role (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type VARCHAR(20) 
);

INSERT INTO role (type)
VALUES ('В главных ролях'),
      ('Роли дублировали');



CREATE TABLE film_person (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    role_id int NOT NULL,
    constraint person_role foreign key (role_id) references role(id)
);
    
INSERT INTO film_person (name, role_id)
VALUES ('Том Хэнкс', '1'),
		('Дэвид Морс', '1'),
		('Бонни Хант', '1'),
		('Майкл Кларк Дункан', '1'),
		('Джеймс Кромуэлл', '1'),
		('Майкл Джитер', '1'),
		('Грэм Грин', '1'),
		('Даг Хатчисон', '1'),
		('Сэм Рокуэлл', '1'),
		('Барри Пеппер', '1'),
		('Всеволод Кузнецов', '2'),
		('Владимир Антоник', '2'),
		('Любовь Германова', '2'),
		('Валентин Голубенко', '2'),
		('Александр Белявский', '2');



CREATE TABLE film_film_person (
        film_id int references film(id),
        film_person_id int references film_person(id),
        constraint film_person_key primary key (film_id, film_person_id)     
    );

INSERT INTO film_film_person (film_id, film_person_id)
VALUES (1, 1),
		(1, 2),
		(1, 3),
		(1, 4),
		(1, 5),
		(1, 6),
		(1, 7),
		(1, 8),
		(1, 9),
		(1, 10),
		(1, 11),
		(1, 12),
		(1, 13),
		(1, 14),
		(1, 15);



CREATE TABLE job (
     id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_title VARCHAR(20) NOT NULL
);

INSERT INTO job (job_title)
VALUES ('Режиссер'),
('Сценарий'),
('Продюсер'),
('Оператор'),
('Композитор'),
('Художник'),
('Монтаж');



CREATE TABLE person (
        id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name VARCHAR(50) NOT NULL,
        jobe_id int NOT NULL,
        film_id int NOT NULL,
        constraint person_jobe foreign key (jobe_id) references job(id),
		constraint person_film foreign key (film_id) references film(id)
    );

INSERT INTO person (name, jobe_id, film_id)
VALUES ('Фрэнк Дарабонт', 1, 1),
('Стивен Кинг', 2, 1),
('Дэвид Валдес', 3, 1),
('Дэвид Тэттерсолл', 4, 1),
('Томас Ньюман', 5, 1),
('Теренс Марш', 6, 1),
('Ричард Фрэнсис-Брюс', 7, 1);



CREATE TABLE genre (
        id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name VARCHAR(50) NOT NULL
    );

INSERT INTO genre (name)
VALUES ('драма'),
        ('фэнтези'),
        ('криминал');



CREATE TABLE film_genre (
        film_id int references film(id),
        genre_id int references genre(id),
        constraint film_genre_pkey primary key (film_id, genre_id)             
    );

INSERT INTO film_genre (film_id, genre_id)
VALUES (1, 1),
		(1, 2),
		(1, 3);



CREATE TABLE country (
        id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name VARCHAR(30) NOT NULL
    );

    INSERT INTO country (name)
VALUES ('США'),
        ('Германия'),
        ('Греция'),
        ('Норвегия'),
        ('Финляндия'),
        ('Швеция'),
        ('Италия'),
        ('Франция'),
        ('Испания');



CREATE TABLE spectators (
        id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        country_id int NOT NULL,
        quantity int,
        film_id int NOT NULL,
        constraint country_film foreign key (country_id) references country(id),
		constraint spectators_film foreign key (film_id) references film(id)
    );

    INSERT INTO spectators (country_id, quantity, film_id)
VALUES (1, 26000000, 1),
        (2, 2107877, 1),
        (3, 182000, 1),
        (4, 110510, 1),
        (5, 32953, 1),
        (6, 132085, 1),
        (7, 1742730, 1),
        (8, 1714080, 1),
        (9, 692551, 1);